### PR TITLE
Add hideCurrentSnackBar for showing instantly

### PR DESCRIPTION
**Pull request by jja08111**
If diffrent snackBar is shown, DoubleBackToCloseApp.snackBar is not shown instantly.

So, I want to add Scaffold.of(context).hideCurrentSnackBar() in _handleWillPop Function.

### CODE REVIEW

**Comment by ghost** [comment]
This seems to make total sense.

Please, add a test and take a look at my comment so I can accept your PR :)

**Comment by ghost** [comment]
@jja08111 I'm not quite sure what you're doing here. This repo already has a [workflow to run the tests](https://github.com/hcbpassos/double_back_to_close_app/blob/master/.github/workflows/main.yml).

**Comment by jja08111** [comment]
@hugocbpassos Sorry, I didn't know how to test the PR.

**Comment by ghost** [comment]
@jja08111 That's not what I meant by "add a test". My apologies.

I want you to write a new test in [test/double_back_to_close_app_test.dart](https://github.com/hcbpassos/double_back_to_close_app/blob/master/test/double_back_to_close_app_test.dart) which proofs that, when there's another snack-bar currently visible, this widget hides it out and shows up the snack-bar provided to `DoubleBackToCloseApp`.

If you are not really used to Flutter's testing framework, I can work on those tests for you in the weekend :)

**Comment by ghost** [comment]
Note to myself: Those commits about the workflow must vanish, so in order to avoid having to rewrite git's history or resubmitting the PR, I should squash before merging.

**Comment by hcbpassos** [comment]
I fixed some conflicts caused by #16.

**Comment by hcbpassos** [comment]
I added the test so this should be good to go.

Thanks for opening this PR  :)

**Pull request merged**
